database:
  database: skyportal_test
  user: skyportal
  host: localhost
  port: 5432
  password:

server:
  auth:
    debug_login: True
    google_oauth2_key:
    google_oauth2_secret:

invitations:
  enabled: False
  days_until_expiry: 3
  email_subject: "You've been invited to collaborate on SkyPortal"
  email_body_preamble: | # This can include HTML tags
    Welcome to <b>SkyPortal</b>!
    <br />
    Some other text here.
  from_email: # This needs to be set to a valid, Sendgrid-registered address in config.yaml
  sendgrid_api_key: # This needs to be obtained via Sendgrid setup on their site
